_target_: ct_laboratory.linear_system.composite.CompositeLinearSystem
matrix_operators:
  - _target_: ct_laboratory.linear_system.scalar.Scalar
    scalar: 2.0
  - _target_: ct_laboratory.linear_system.scalar.Scalar
    scalar: 3.0 